run the pre-commit on all files

diff --git a/get-removed-labels b/get-removed-labels
--- a/get-removed-labels
+++ b/get-removed-labels
@@ -2,37 +2,43 @@
 
 # Function to display usage
 usage() {
-    echo "Usage: $0 -o owner -n name -p pr_number"
-    exit
+	echo "Usage: $0 -o owner -n name -p pr_number"
+	exit
 }
 
 # Parse command-line arguments
 while getopts ":o:n:p:" opt; do
-  case $opt in
-    o) owner="$OPTARG"
-    ;;
-    n) name="$OPTARG"
-    ;;
-    p) pr_number="$OPTARG"
-    ;;
-    \?) echo "Invalid option -$OPTARG" >&2
-        usage
-    ;;
-    :) echo "Option -$OPTARG requires an argument." >&2
-       usage
-    ;;
-  esac
+	case $opt in
+	o)
+		owner="$OPTARG"
+		;;
+	n)
+		name="$OPTARG"
+		;;
+	p)
+		pr_number="$OPTARG"
+		;;
+	\?)
+		echo "Invalid option -$OPTARG" >&2
+		usage
+		;;
+	:)
+		echo "Option -$OPTARG requires an argument." >&2
+		usage
+		;;
+	esac
 done
 
 # Check if all required arguments are provided
 if [ -z "$owner" ] || [ -z "$name" ] || [ -z "$pr_number" ]; then
-    usage
+	usage
 fi
 
-response=$(gh api graphql \
-    --paginate \
-    -F number=$pr_number -F owner=$owner -F name=$name \
-    -f query='
+response=$(
+	gh api graphql \
+		--paginate \
+		-F number=$pr_number -F owner=$owner -F name=$name \
+		-f query='
     query($endCursor: String, $owner: String!, $name: String!, $number: Int!) {
         repository(owner: $owner, name: $name) {
           pullRequest(number: $number) {
